### ISSUE TITLE
PHP Fatal error:  Access to undeclared static property: Smarty::$_IS_WINDOWS 

### ISSUE THREAD

**Issue by fnami0316** [smarty-php/smarty#34] opened 2015-05-14 05:48 UTC
Please forgive my clumsy English .

where it was set as follows in composer.json, since version 3.1.23 has been installed , I have been recognized as this is the latest stable version.

> "require": {
>    "smarty / smarty": "~ 3.1"
> }

However , errors that did not occur in version 3.1.21 has occurred .

> PHP Fatal error: Access to undeclared static property: Smarty :: $ _ IS_WINDOWS in .....

Since there is no way , I have specified to use the 3.1.21 to composer.json.

>"require": {
>  "smarty / smarty": "3.1.21"
>}

Do not the people who have the same problem ?

**Comment by uwetews** [comment] 2015-05-14 08:42
I can't reproduce your problem.  Smarty :: $ _ IS_WINDOWS is declared in line 206 of the Smarty class.

Which peace of code does create the error?

**Comment by fnami0316** [comment] 2015-05-14 10:19
> Which peace of code does create the error?

The error has occurred at "vendor/smarty/smarty/libs/sysplugins/smarty_internal_write_file.php on line 56".

       /*
         * Windows' rename() fails if the destination exists,
         * Linux' rename() properly handles the overwrite.
         * Simply unlink()ing a file might cause other processes
         * currently reading that file to fail, but linux' rename()
         * seems to be smart enough to handle that for us.
         */
        if (Smarty::$_IS_WINDOWS) {  // ←this line!
            // remove original file
            @unlink($_filepath);
            // rename tmp file
            $success = @rename($_tmp_file, $_filepath);
        } else {
            // rename tmp file

**Comment by uwetews** [comment] 2015-06-04 06:28
All other applications don't have this problem I close this issue for now.

**Closed by uwetews** 2015-06-04 06:28 UTC
