### ISSUE TITLE
smarty isset not working notice Undefined offset 3.1.32v and 3.1.33v

### ISSUE THREAD

**Issue by jvalencia74** [smarty-php/smarty#499] opened 2018-10-17 23:59 UTC
when trying to update it happens to me in both versions and it is in a section loop 

{section name=field loop=$result} 
{if ((isset($result[field].changeState)) and ($role_update == "1"))} 
{else} 
{/if} 
{/section} 

template return error 

smarty\ce7fa0ecf0a71469a5f7beae553a6f8123a19440_0.file.Maintenance.Dispatchers.input.tpl.php:203] Undefined index: changeState 

it only happens when reading an array with section 

I have the same error in several templates with different index 

works well in 3.1.30v

tks

**Comment by mylemans** [comment] 2018-10-24 16:46
I have the same issue, almost (if not all) my sections broke!

**Comment by pszalko** [comment] 2018-11-23 13:21
I can confirm this issue for me too. Smarty code inside `{section}` does not generate `isset()`.

**Comment by jeckyl** [comment] 2019-01-10 16:04
Hi,
I also confirm this concern. Quite embarrassing in the development of testing its variables to realize that the test itself does not work.

**Comment by tmcreativeltd** [comment] 2019-03-08 09:43
Come on Smarty... surely this is what isset is for? Any plans on a fix?

**Comment by pszalko** [comment] 2019-03-12 11:31
I have encountered this issue again...

Here is some follow up if and workaround that I found.

**Use case:**
The following Smarty code raised PHP Notice:
```
<li class="{if isset($availabilityDates[$group->getId()][$dateString]) == true} selected{/if}"
```

After short inspection:

**1. Investigation:**
I have found out that this issue might be related to implementation in `smarty_internal_templatecompilerbase.php:633` (for Smarty v3.1.33):
```php
$pa[] = (strpos($p, '(') === false) ? ('isset(' . $p . ')') : ('(' . $p . ' !== null )');
```
Variable `$p` holds the exact line of the template that is being parsed by Smarty.
In that particular line my template code is `isset(... [$group->getId()]...)`.
Do you see already what's going on? Smarty looks for `(` char, and if found `isset(...)` is stripped and replaced by `!== null` in compiled template.

**2. Workaround:**
Remove any parenthesis from argument of `isset()` method.

Here is workaround implementation for my use case:
```
{assign var="groupId" value=$group->getId()}
<li class="{if isset($availabilityDates[$groupId][$dateString]) == true} selected{/if}"
```

I hope this knowledge will help someone in Smarty team to resolve this issue.

**Comment by wisskid** [comment] 2020-01-28 10:21
Duplicate of #453

**Closed by wisskid** 2020-01-28 10:21 UTC
Labels: duplicate
