### ISSUE TITLE
PHP 8.1: Deprecated notices for modifier.date_format.php

### ISSUE THREAD

**Issue by m-arimoto** [smarty-php/smarty#805] opened 2022-09-20 05:59 UTC
Hi,

`Deprecated: Function strftime() is deprecated in smarty/smarty/libs/plugins/modifier.date_format.php on line 81`

**Comment by wisskid** [comment] 2022-09-20 20:20
Duplicate of #672

**Closed by wisskid** 2022-09-20 20:20 UTC
