### ISSUE TITLE
extends children block (invalid result)

### ISSUE THREAD

**Issue by Invision70** [smarty-php/smarty#200] opened 2016-03-08 18:24 UTC
After upgrade from 3.1.5 to 3.1.30-dev i have a problem:

File: admin/table.tpl
```
{block name="content"}
.. some code..
   {block name="table"}
     // ex. return:
     <b>12345</b>
    {/block}
.. some code..
{/block}

```
File: admin/users.tpl

```
{extends file="admin/table.tpl"}

{block name="table"}
 // ex. need return:
  <b>67890</b>
{/block}
```
-------------------------
Result is 12345, but I need to value: 67890.
Block `table` in admin/users.tpl is not extends.

**Comment by uwetews** [comment] 2016-03-08 20:25
I can't reproduce your problem 

$smarty->display('admin/users.tpl') does return the expected result of 67890

**Comment by uwetews** [comment] 2016-07-23 21:03
As this problem cant be reproduced I close this issue now

**Closed by uwetews** 2016-07-23 21:03 UTC
