### ISSUE TITLE
"too many shorthand attributes" error

### ISSUE THREAD

**Issue by bhaal-nig** [smarty-php/smarty#568] opened 2020-01-28 14:03 UTC
# Current state

## Good examples
When custom template function is called with named argument:

```
    {funcName arg=argumentValue}
```
in function body arg can be accessed:
```
    $arg = $params['arg'];
```

---

When more named arguments are passed:
```
 {funcName arg=argumentValue arg2=argumentValue2}
```
in function body args can be accessed:
```
    $arg1 = $params['arg'];
    $arg2 = $params['arg2'];
```

---

When more shorthand args are passed:
```
    {funcName argumentValue argumentValue2}
```
in function body args can be accessed:
```
    $arg1 = $params[0];
    $arg2 = $params[1];
```

## Unexpected behavior (BUG)

But when **one** shorthand arg is passed:
```
    {funcName argumentValue}
```
The "too many shorthand attributes" error is triggerd.

# Expected behavior

When **one** shorthand arg is passed (it should be the same as when more shorthand args are passed):
```
    {funcName argumentValue}
```
in function body arg can be accessed:
```
    $arg = $params[0];
```

**Comment by wisskid** [comment] 2020-01-28 14:40
did you use some for of custom compile stap to define shorttag attributes? The example you give creates an error for any number of shorthand attributes:
```
<?php
require_once './vendor/autoload.php';
$smarty = new Smarty();
$smarty->registerPlugin("function","funcName", function ($params, $smarty) { return ''; });
$smarty->display('string:{funcName argumentValue argumentValue2}');
```
returns
```
PHP Fatal error:  Uncaught  --> Smarty Compiler: Syntax error in template "string:{funcName argumentValue argumentValue2}"  on line 1 "{funcName argumentValue argumentValue2}" too many shorthand attributes <-- 
  thrown in /home/workspace/smarty/smarty/libs/sysplugins/smarty_internal_templatecompilerbase.php on line 1
```

**Comment by bhaal-nig** [comment] 2020-01-28 15:46
Im sorry, it was caused by cached result (for case "When more shorthand args are passed").

But after this patch https://github.com/smarty-php/smarty/pull/569 is possible to use one/more shorthands in custom func call and then they are accessible by `$params[0]` in func body.

So its not a BUG, but i will appriciate that shorter func calls.
```
{func arg arg2 arg3}
instead of:
{func arg1=arg arg2=arg2 arg3=arg3}
```

**Comment by wisskid** [comment] 2020-01-29 15:05
Alright, i've renamed your PR to indicate this is not a bug but an enhancement, and referenced it in https://github.com/smarty-php/smarty/issues/165 where @cdp1337 suggested the same change. I'll close this issue now.

**Closed by wisskid** 2020-01-29 15:05 UTC
Labels: waiting
