### ISSUE TITLE
problems with smarty_mb_str_replace PHP >= 7.1

### ISSUE THREAD

**Issue by modGTB** [smarty-php/smarty#549] opened 2019-07-30 11:33 UTC
There ist a problem with the "replace" modifier in combination with ISO-8859-1 and PHP >= 7.1
You get an empty string back in case the string contains german umlauts (öäü).

**Comment by AnrDaemon** [comment] 2019-09-15 21:09
Could you please fork https://github.com/AnrDaemon/test-001 and reproduce your issue in a branch cloned from the master?

**Comment by cmanley** [comment] 2019-09-24 15:42
I'd like to add to this (after having issues with latin encoded German characters in Smarty 3.1.33)....
The issue is not related to the PHP version.
What's happening is that "replace" calls "smarty_mb_str_replace" if the MB extension is loaded, but the latter function does not take the encoding set in Smarty::$_CHARSET into account, assuming that the text is encoded in UTF-8 which causes the line with "mb_split(preg_quote(..." to return false. One of the reasons is that mb_split() uses the encoding defined by mb_regex_encoding() which Smarty sets nowhere.
So the fix is fairly simple: make smarty_mb_str_replace use Smarty::$_CHARSET and be very careful and considerate of encodings when using mb_split and preg_* functions. 

I noticed a few more minor issues related to encoding in Smarty while digging into this:
1. In Smarty.class.php, the comment above the define of SMARTY_RESOURCE_CHAR_SET says "deprecated in favor of Smarty::$_CHARSET". The problem with that is, is that Smarty code accesses Smarty::$_CHARSET using the hard-coded class name prefix instead of static::$_CHARSET, which makes overriding troublesome. 
2. The constructor in Smarty.class.php modifies the applications internal encoding (this is a no-no) by calling mb_internal_encoding() instead of adapting itself to that encoding.
3. Custom child classes of Smarty that set Smarty::$_CHARSET in their constructors have to do so before calling parent::__construct() or else Smarty::$_UTF8_MODIFIER will be set wrong.
4. Because the Smarty encoding related properties are statics, it makes it impossible to use 2 Smarty instances in 2 different encodings simultaneously (e.g. one for legacy SMS templates in latin1, and one for UTF-8 encoded HTML pages). Although rare, a (very) good Smarty design will not fail then.

**Comment by modGTB** [comment] 2019-09-24 16:32
I have fixed the problem with adding these lines:
`        if (is_callable('mb_regex_encoding')) {
            mb_regex_encoding(Smarty::$_CHARSET);
        }
`

after 
`        if (is_callable('mb_internal_encoding')) {
            mb_internal_encoding(Smarty::$_CHARSET);
        }
`

**Comment by cmanley** [comment] 2019-09-24 18:16
That's almost a good solution, except for 1 problem: mb_regex_encoding() supports much less encodings than mb_internal_encoding(). See the comments below the mb_regex_encoding documentation. I'm afraid, if you want to use mb_split(), then you'll have to translate the given input into utf-8 (or whatever encoding has the widest coverage), operate on it, and then translate the result back into the expected encoding. Perhaps writing a alternative mb_trim-like function that supports an encoding parameter is better. It's a nasty problem.

**Comment by cmanley** [comment] 2019-09-24 18:33
think this will fix it, by replace the last "else" block in plugins/shared.mb_str_replace.php with this:
`
        } else {
            $want_encoding = 'UTF-8';
            $must_transcode = function_exists('mb_convert_encoding') && strcasecmp(Smarty::$_CHARSET, $want_encoding);
            if ($must_transcode) {
                $search  = mb_convert_encoding($search , $want_encoding, Smarty::$_CHARSET);
                $replace = mb_convert_encoding($replace, $want_encoding, Smarty::$_CHARSET);
                $subject = mb_convert_encoding($subject, $want_encoding, Smarty::$_CHARSET);
            }
            $parts = preg_split('/' . preg_quote($search, '/') . '/u', $subject);
            $count = count($parts) - 1;
            $subject = implode($replace, $parts);
            if ($must_transcode) {
                $search  = mb_convert_encoding($search, Smarty::$_CHARSET, $want_encoding);
            }
        }
`
It needs testing though.

**Comment by AnrDaemon** [comment] 2019-09-25 18:37
You can use `{}` as RE delimiters, avoiding much of the "quote this, quote that" issue.
But without a test case, all your code is for nothing.

**Comment by cmanley** [comment] 2019-09-25 19:20
...until you get a search string with either { or } in it. 
It's not for nothing for who does what I did: copy + fix the function and load it before Smarty loads.

**Comment by AnrDaemon** [comment] 2019-09-25 19:55
Sorry, I did mean to say "quote this, don't quote that".
`preg_match('{' . preg_quote($string) . '}u');` is perfectly safe.

**Comment by AnrDaemon** [comment] 2019-09-25 19:57
> It's not for nothing for who does what I did: copy + fix the function and load it before Smarty loads.

Without a clear test case you can't be sure if the fix is working, or if there's no sideeffects of your fix. Or that your fix won't be accidentally dropped in a future refactoring.

**Comment by cmanley** [comment] 2020-04-14 23:29
Still broken in 3.1.36

**Comment by Tomcraft1980** [comment] 2020-04-22 19:19
Hmmm, that is really sad!

**Comment by cmanley** [comment] 2020-05-01 22:24
> > It's not for nothing for who does what I did: copy + fix the function and load it before Smarty loads.
> 
> Without a clear test case you can't be sure if the fix is working, or if there's no sideeffects of your fix. Or that your fix won't be accidentally dropped in a future refactoring.

Here's the forked test case demonstrating the issue and the fix:
https://github.com/cmanley/test-001

**Comment by AnrDaemon** [comment] 2020-05-03 21:47
I see the issue, however, the fix is not appropriate. The real problem is that

  1. Smarty is changing `mb_internal_encdoing`, consequently breaking entire environment;
  2. `mb_split` is using *two encodings,* and it does that inconsistently. Bad stuff.

This can be fixed in two ways. One is quick and dirty. One is correct and very, very tedious.

**Comment by Tomcraft1980** [comment] 2020-05-03 21:51
Good news! So there is a chance to see this issue be fixed in an upcoming release? ;-)

**Comment by AnrDaemon** [comment] 2020-05-03 22:15
I'm tinkering with the code as we speak. May be, just may be, I will have a fix. I already have a regression test case, so this should be covered.

**Comment by Tomcraft1980** [comment] 2020-05-03 22:21
Thanks in advance! =)

**Comment by AnrDaemon** [comment] 2020-05-03 22:22
Another problematic point is that you can not actually rely on `Smarty::$_CHARSET` as it can be changed AFTER initialization.

**Comment by AnrDaemon** [comment] 2020-05-03 22:25
`plugins/modifier.escape.php` needs an investigation and coverage analysis.

**Comment by AnrDaemon** [comment] 2020-05-04 17:58
It seems I'm going to fix A LOT of stuff in process. >.< There's lots of PHP incompatibilities and the test suite is not configured to run on minimum advertised PHP version.

**Comment by bLeveque42** [comment] 2020-11-09 02:20
I was running into an obscure issue in the PrestaShop back-office, and nailed it down to the replace modifier.
Every time I'd call |replace, I'd just get a blank page after that, even with smarty_debugging and error_reporting turned on.

It seems it was this exact same issue, and it was resolved once I installed php7.3-mbstring.

Thank you for the fix, this is gonna help a lot of people!

**Comment by wisskid** [comment] 2023-01-31 09:15
This was fixed in #740.

**Closed by wisskid** 2023-01-31 09:15 UTC
