### ISSUE TITLE
forgot to bump version number in 3.1.35 release?

### ISSUE THREAD

**Issue by joebordes** [smarty-php/smarty#597] opened 2020-06-18 21:42 UTC
https://github.com/smarty-php/smarty/blob/master/libs/Smarty.class.php#L30

https://github.com/smarty-php/smarty/blob/v3.1.35/libs/Smarty.class.php#L115

**Comment by AnrDaemon** [comment] 2020-07-30 14:33
Fixed with https://github.com/smarty-php/smarty/releases/tag/v3.1.36

**Comment by Bigbear7** [comment] 2020-08-17 14:21
Shouldcthe smarty homepage be updated since it announces Smarty 3.1.35?

**Comment by scottchiefbaker** [comment] 2020-08-17 16:07
This is a duplicate of #588 

In other words... it's a known issue :)

**Closed** 2020-08-23 20:03 UTC
