### ISSUE TITLE
isset on array

### ISSUE THREAD

**Issue by beaceberq** [smarty-php/smarty#498] opened 2018-10-09 14:24 UTC
`isset` is not generated when we specify the object's property / method as an index

Example:
Code on .tpl:
`{if isset($specialOffers[$category->getId()])}gray{/if}`
Generated code:
`<?php if ((($_smarty_tpl->tpl_vars['specialOffers']->value[$_smarty_tpl->tpl_vars['category']->value->getId()] !== null ))) {?>gray<?php }?>`

**Comment by pszalko** [comment] 2018-11-23 13:20
Any update on this issue?

**Comment by nenetchi** [comment] 2019-02-22 06:20
+1 for backticks substitution in array index

- PHP 7.0.33/7.3.1
- Smarty 3.1.33

Template
```
{if isset($foo["prefix_`$bar`"])}
1
{/if}
```

will generate

```php
if ((($_smarty_tpl->tpl_vars['foo']->value["prefix_".((string)$_smarty_tpl->tpl_vars['bar']->value)] !== null ))) {?>
1
<?php }
```

with `isset` missing

**Comment by pszalko** [comment] 2019-03-12 11:34
I believe this is similar issue to #499 
and I hope the workaround from https://github.com/smarty-php/smarty/issues/499#issuecomment-471963311 will help.

Anyway, I hope to see it resolved soon.

**Comment by wisskid** [comment] 2020-01-28 10:21
Duplicate of #453

**Closed by wisskid** 2020-01-28 10:21 UTC
Labels: duplicate
