### ISSUE TITLE
With Php 8.1 : : Function strftime() is deprecated

### ISSUE THREAD

**Issue by piolet** [smarty-php/smarty#763] opened 2022-05-28 11:36 UTC
Since PHP 8.1, `strftime` is depcrecated but, in this modifier, it's still used :
https://github.com/smarty-php/smarty/blob/629504485f3c4df7d06f9d4b79f2f4ff9bdbeb55/libs/plugins/modifier.date_format.php#L81

You can use `IntlDateFormatter` or `DateTimeImmutable::createFromFormat` to replace it : https://php.watch/versions/8.1/strftime-gmstrftime-deprecated

**Comment by wisskid** [comment] 2022-05-28 14:00
Duplicate of a few existing issues.

**Closed by wisskid** 2022-05-28 14:00 UTC

**Comment by piolet** [comment] 2022-05-28 14:52
Which existing issue ?
The ones I found did not mention this module. At least, it seems to me.

**Comment by wisskid** [comment] 2022-05-28 15:44
#672 was the first search result for me.
