### ISSUE TITLE
template handling order with extendsall: vs file: as default resource type

### ISSUE THREAD

**Issue by chilek** [smarty-php/smarty#374] opened 2017-06-29 12:36 UTC
I've prepared exampe which demonstrates the occured problem:
https://www.chilan.com/smarty-test-3.tar.xz

You have two possible variants:
1. With commented out the following lines:
```php
//$SMARTY->setMergeCompiledIncludes(true);
//$SMARTY->setDefaultResourceType('extendsall');
```
In this variant **header.html** and **footer.html** files are handled with order as I expect - first found file is loaded.

2. After uncommenting earlier mentioned lines **header.html** and **footer.html** files are handled in reverse order - I mean files from within last template directory are loaded.

Is it possible in this variant to get effect in which I have:
```php
$SMARTY->setMergeCompiledIncludes(true);
$SMARTY->setDefaultResourceType('extendsall');
```
and **header.html** and **footer.html** are handled in the same order as handling of **content.html** files?

Reference: https://github.com/chilek/lms-plus/issues/291

**Comment by uwetews** [comment] 2017-10-07 15:15
Sorry for the  laate reply. I was longer term ill.

Call the header and footer by explicit specifing the file: resource.

{include file="file:header.html"}

{block name="content"}
<p>classic content</p>
{/block}

{include file="file:footer.html"}

**Comment by chilek** [comment] 2017-10-09 10:48
@uwetews but this doesn't resolve the problem, because in plugins we use template inheritance also for header.html and footer.html, as we want to modify their contents.

**Comment by chilek** [comment] 2017-10-10 11:05
But this would require a lot of changes - a few hundred files :(

**Comment by chilek** [comment] 2018-10-02 09:13
3.1.33:

```php
$SMARTY->setMergeCompiledIncludes(true);
$SMARTY->setDefaultResourceType('extendsall');
```

Only included templates are loaded with 'extendsall:' prefix, I mean:
```smarty
{include file="contents.html"}
```
impacts on compiled template as follows:
```php
  'includes' => 
  array (
    'file:[1]layout.html' => 1,
    'extendsall:content.html' => 1,
    'file:[1]content.html' => 1,
  ),

but:
```php
$SMARTY->display('layout.html');
```
uses only 'file:' resource type (as in above compiled template snippet).
Tried to use:
```php
$SMARTY->display('extendsall:layout.html');
```
and it doesn't fix the situation.

Would be perfect to work with and wihout 'extendsall:' resource type for display() method.
@uwetews can you help me anyhow?

**Comment by uwetews** [comment] 2018-10-02 11:00
What you see is correct. The extendsall resource is a frame which holds all individual file resources for the templates with same name out of different folders. If you do not set the mergeCompiledInclude flag you will get for each template a compiled file and one additional for the extendsall frame resource. So if you have 2 templates with same name you get 3 files. It has not the best performance.

If you merge the includes some performance optimization is in effect. The first template found will create internally the extendsall resource which includes the file resource for the first template. However if no other template with same name will be found it falls back to a simple file resource to get rid of the not needed overhead reducing memory usage and execution time.

In your example you have just one layout.html file. for that reason will in the compiled file just as a simple file resource. The first of the included content.html template files will get extendsall resouce type we cause it must chain the rendering to the other template file with same name. 

Its not a bug, but optimization feature.

**Comment by chilek** [comment] 2018-10-02 11:54
The clue is that it doesn't find layout.html in other template dir.

**Comment by chilek** [comment] 2018-10-02 11:57
I try to change template such way that I put template file with the same name as original but in other template directory (added to template dir collection), but Smarty always takes only original file for template pointed by:
```php
$SMARTY->display('layout.html');
```
Subtemplates inclued from layout.html template uses extendsall resource type, but main layout.html not. Event if we prepend this template file name with 'extendsall:' resource type :(

**Comment by chilek** [comment] 2018-10-02 12:12
In my problematic scenario we have 2 template files with the same name but located in different template directories - layout.html. Let's assume that 1:layout.html, 2:layout.html mean template files from related template directories configured with:
```php
$SMARTY->AddTemplateDir(
                array(
                        'directory_1',
                        'directory_2',
                )
        );
```
We expect to layout.html file load from directory_1, but it loads from directory_2 :(

**Comment by uwetews** [comment] 2018-10-02 12:50
addTemplateDir() will append the directories to whatever the template_dir setting was before (default value)? So 'directory_1' is not the first folder searched. 
use setTemplateDir() to look for sure just in the two folders in the correct order.

What but it should see both templates anyway. Are you sure that the template in directory_1 is readable?

What happens if you setTemplateDir just to 'directory_1'?

Strange does work at my place like a charm

**Comment by chilek** [comment] 2018-10-02 13:13
I asked colleague to describe the problem with more details. Will update this issues when get answer from him.

**Comment by chilek** [comment] 2018-10-02 13:50
Ok - I've prepared problem isolated test:

**index.php** file:
```php
$SMARTY = new Smarty;
$SMARTY->setMergeCompiledIncludes(true);
$SMARTY->setDefaultResourceType('extendsall');
$SMARTY->AddTemplateDir(array(
  'directory_1',
  'directory_2',
));
$SMARTY->display('test.html');
```

**test.html** from _directory\_1_:
```html
test_1
```

**test.html** from _directory\_2_:
```html
test_2
```

In web browser we have the output of:
`test_2`

**Comment by uwetews** [comment] 2018-10-02 15:49
The extendsall resource is a special form of template inheritance where templates with same name create parent child relation ships. the last template loaded will be the parent template. Like with the extends resource the parent template is the only template which also displays text and executes code outside from block tags. I think that's the reason why you see only the test_2 output

**Comment by chilek** [comment] 2018-10-02 16:41
@uwetews so how could I fix the problem?

**Comment by uwetews** [comment] 2018-10-02 18:59
I need to know how your the template content looks like. And what you want to do. I remember from the older discussions that you used some very special solutions to merge and arrange  the content of the templates. give me some examples please. It might be that the extendsall resource working similar like the normal extends resource is not the right solution and a new custom  resource would do it. 
I need more details

**Comment by chilek** [comment] 2018-10-02 19:40
I've prepared files for two test case scenarios. Here you have all files:
https://www.chilan.com/smarty-test-4.tar.xz
1. When you call **/smarty-test-4/display.php** you get `default content`.
2. When you call **/smarty-test-4/extendsall.php** you get `modified content`.

For my perspective it means that extendsall case causes that template file from _earlier_ template directory is taken, and for display case file from _later_ template directory is taken.
My goal to achieve is effect in which I get `modified content` output indepdently from usage type.
It that the only way for that to _inject_ **content-display.html** from **templates-modified** directory is to use:
```smarty
{block name="content"}
  ...
{/block}
?
It would mean that I should outfit all templates in blocks and all replacing templates should use these blocks. But I'd like to avoid this and simultaneously use both methods of replacing templates in _earlier_ template directory.

**Comment by wisskid** [comment] 2023-01-31 09:43
@chilek this issue is 5+ years old. I'm closing this now to clean up. Hopefully you have found a solution. If not, please open a discussion.

**Closed by wisskid** 2023-01-31 09:43 UTC
