### ISSUE TITLE
Huge amount of warnings on PHP8

### ISSUE THREAD

**Issue by noximo** [smarty-php/smarty#648] opened 2021-03-18 14:11 UTC
We recently switched to PHP8. Smarty works fine but generates a lot of warnings due to missing variables. I know that Smarty 4 will have setting to deal with this and that it is supposed to be released soon-ish but I would like to know if there's some solution I can try in the meantime to keep the log folders clean.

**Comment by redcuillin** [comment] 2021-03-21 04:16
sudo apt-get install php7.4?

I know that sounds flippant, and I don't mean to sound unfriendly. But if Smarty doesn't support PHP8 yet, why are you using it with PHP8? PHP8 is very new, and huge amounts of code used widely in website dependencies has not transitioned yet. PHP7.4 is still fully supported and there are no security concerns. The simplest answer is 'be patient' before rushing to install PHP8 in a production environment.

If you must have 8, and Smarty works barring the warnings, fork it and fix the unset variables yourself. Or turn off PHP warnings (you can still get more serious errors logged) in php.ini.

**Comment by noximo** [comment] 2021-03-21 13:51
> fork it and fix the unset variables yourself

That's what I wanted to do. I was hoping someone would point me in a direction where I can fix it, because the errors themselves are in the generated files

**Comment by wisskid** [comment] 2021-03-21 20:28
Maybe you can give the feature/php8-support branch? You can see it here https://github.com/smarty-php/smarty/pull/629

**Comment by wisskid** [comment] 2021-03-21 20:29
Closing this as a duplicate of https://github.com/smarty-php/smarty/issues/605

**Closed by wisskid** 2021-03-21 20:29 UTC
